import type {
  NLUExtractionResult,
  NLUProcessOptions,
  ExtractedEntity,
  ExtractedConcept,
  LLMOutputShape,
  IntentResult,
} from './types.js';
import type { ILLMProvider } from '../../providers/llm/llmProvider.interface.js';
import { defaultLLMProvider } from '../../providers/llm/llmProvider.factory.js';
import { DynamicSchemaRegistry, defaultSchemaRegistry } from '../../schemas/dynamicSchema.js';
import { IntentRegistry, defaultIntentRegistry } from './intentRegistry.js';
import { OntologyRegistry, defaultOntologyRegistry } from '../../ontology/ontologyRegistry.js';
import { DeterministicExtractor } from './deterministicExtractor.js';
import { DynamicPromptBuilder } from './dynamicPromptBuilder.js';
import { ValidationError } from '../../utils/errors.js';
import { logger } from '../../utils/logger.js';
import type { FieldDefinition } from '../../schemas/types.js';

export class NLUEngine {
  private schemaRegistry: DynamicSchemaRegistry;
  private intentRegistry: IntentRegistry;
  private ontologyRegistry: OntologyRegistry;
  private llmProvider: ILLMProvider;

  constructor(options?: {
    schemaRegistry?: DynamicSchemaRegistry;
    intentRegistry?: IntentRegistry;
    ontologyRegistry?: OntologyRegistry;
    llmProvider?: ILLMProvider;
  }) {
    this.schemaRegistry = options?.schemaRegistry || defaultSchemaRegistry;
    this.intentRegistry = options?.intentRegistry || defaultIntentRegistry;
    this.ontologyRegistry = options?.ontologyRegistry || defaultOntologyRegistry;
    this.llmProvider = options?.llmProvider || defaultLLMProvider;
  }

  /**
   * Main entry point to process natural artisan utterance into structured NLU result
   */
  public async process(
    text: string,
    options?: NLUProcessOptions
  ): Promise<NLUExtractionResult> {
    if (!text || !text.trim()) {
      throw new ValidationError('Input utterance cannot be empty');
    }

    const cleanText = text.trim();
    logger.debug({ text: cleanText, sessionId: options?.sessionId }, 'Processing NLU utterance');

    // 1. Deterministic Extraction (fast regex, scripts, known ontology terms)
    const deterministic = DeterministicExtractor.extract(cleanText, this.ontologyRegistry);

    // 2. Build Dynamic System Prompt reflecting active schema, intents, ontology, and conversation draft context
    const systemPrompt = DynamicPromptBuilder.buildNLUSystemPrompt(
      this.schemaRegistry,
      this.intentRegistry,
      this.ontologyRegistry,
      options?.currentDraft
    );

    // 3. LLM Semantic Understanding
    let llmResult: LLMOutputShape = {};
    try {
      const response = await this.llmProvider.generateStructured<LLMOutputShape>(
        cleanText,
        systemPrompt
      );
      llmResult = response.data || {};
    } catch (error) {
      logger.warn(
        { err: error, text: cleanText },
        'LLM semantic parsing failed, falling back to deterministic processing'
      );
    }

    // 4. Intent Detection & Validation against IntentRegistry
    const isCorrection = Boolean(llmResult.isCorrection || deterministic.isCorrectionCandidate);
    let resolvedIntentName: string;

    if (llmResult.intent) {
      const directMatch = this.intentRegistry.getIntent(llmResult.intent);
      if (directMatch) {
        resolvedIntentName = directMatch.name;
      } else {
        const caseMatch = this.intentRegistry
          .getIntents()
          .find((i) => i.name.toLowerCase() === llmResult.intent?.toLowerCase());
        if (caseMatch) {
          resolvedIntentName = caseMatch.name;
        } else {
          logger.warn(
            { unknownIntent: llmResult.intent },
            'Unknown intent returned by LLM, falling back to default/deterministic candidate'
          );
          resolvedIntentName = isCorrection ? 'CORRECT_INFORMATION' : 'CREATE_PRODUCT';
        }
      }
    } else {
      resolvedIntentName = isCorrection ? 'CORRECT_INFORMATION' : 'CREATE_PRODUCT';
    }

    const intentConfidence = llmResult.confidence ?? (deterministic.isCorrectionCandidate ? 0.95 : 0.85);
    const intent: IntentResult = {
      name: resolvedIntentName,
      confidence: intentConfidence,
    };

    // 5. Entity Extraction, Alias Mapping & Grounding (Preserve Unknown Values, Reject Unknown Field Keys)
    const configuredFields = this.schemaRegistry.getFields();
    const validLLMEntities: Record<string, unknown> = {};
    const concepts: ExtractedConcept[] = llmResult.concepts ? [...llmResult.concepts] : [];

    if (llmResult.entities && typeof llmResult.entities === 'object') {
      for (const [rawKey, rawVal] of Object.entries(llmResult.entities)) {
        if (rawVal === undefined || rawVal === null || rawVal === '') continue;

        const fieldDef = this.resolveFieldDefinition(rawKey, configuredFields);
        if (!fieldDef) {
          logger.warn(
            { field: rawKey, value: rawVal },
            'Discarded unconfigured/unknown entity field generated by LLM'
          );
          continue;
        }

        // Ground known concepts or preserve novel artisan concepts
        const groundedValue = this.groundFieldValue(fieldDef, rawVal, cleanText, concepts);
        validLLMEntities[fieldDef.name] = groundedValue;
      }
    }

    // 6. Merging Deterministic + LLM Entities
    // Deterministic extraction provides high-confidence exact matches (e.g. currency numbers),
    // while LLM provides semantic understanding and novel free-form concepts.
    const mergedEntities: Record<string, unknown> = {
      ...validLLMEntities,
      ...deterministic.entities,
    };

    const entityDetails: ExtractedEntity[] = [...deterministic.entityDetails];
    for (const [key, value] of Object.entries(validLLMEntities)) {
      if (!deterministic.entities[key]) {
        const isNovel = concepts.some((c) => c.value === value && c.isKnown === false);
        entityDetails.push({
          field: key,
          value,
          evidence: cleanText,
          confidence: 0.88,
          source: isNovel ? 'UNKNOWN_ARTISAN_CONCEPT' : 'LLM_EXTRACTION',
        });
      }
    }

    // 7. Normalization
    const normalizedEntities = this.schemaRegistry.normalizeDraft(mergedEntities);

    // 8. Conversational State / Contextual Draft Accumulation
    const effectiveDraft = options?.currentDraft
      ? { ...options.currentDraft, ...normalizedEntities }
      : normalizedEntities;

    // 9. Validation & Missing Fields calculation
    const validation = this.schemaRegistry.validateDraft(effectiveDraft);
    const missingFields = this.schemaRegistry.getMissingFields(effectiveDraft);

    // 10. Follow-up Question Formulation for missing information
    let followUpQuestion: string | undefined;
    if (missingFields.length > 0) {
      if (llmResult.followUpQuestion) {
        followUpQuestion = llmResult.followUpQuestion;
      } else {
        followUpQuestion = this.generateFallbackFollowUp(missingFields[0]);
      }
    }

    const detectedLanguage =
      llmResult.language || deterministic.detectedLanguage || options?.languageHint || 'en';

    return {
      intent,
      entities: normalizedEntities,
      entityDetails,
      concepts,
      detectedLanguage,
      isCorrection,
      overallConfidence: Math.min(intentConfidence, 0.95),
      validation,
      missingFields,
      rawText: cleanText,
      followUpQuestion,
    };
  }

  /**
   * Resolves field key against schema names, aliases, and casing variants
   */
  private resolveFieldDefinition(
    key: string,
    fields: FieldDefinition[]
  ): FieldDefinition | undefined {
    const cleanKey = key.trim().toLowerCase().replace(/[-_\s]/g, '');

    for (const field of fields) {
      if (field.name.toLowerCase() === key.toLowerCase()) return field;
      const cleanFieldName = field.name.toLowerCase().replace(/[-_\s]/g, '');
      if (cleanFieldName === cleanKey) return field;

      if (field.aliases) {
        for (const alias of field.aliases) {
          const cleanAlias = alias.toLowerCase().replace(/[-_\s]/g, '');
          if (cleanAlias === cleanKey || alias.toLowerCase() === key.toLowerCase()) {
            return field;
          }
        }
      }
    }

    return undefined;
  }

  /**
   * Grounds field values against ontology when recognized, while preserving novel artisan concepts
   */
  private groundFieldValue(
    fieldDef: FieldDefinition,
    val: unknown,
    evidenceText: string,
    concepts: ExtractedConcept[]
  ): unknown {
    if (fieldDef.name === 'craft_type' && typeof val === 'string') {
      const craft = this.ontologyRegistry.findCraft(val);
      if (craft) {
        concepts.push({
          name: 'craft_type',
          value: craft.name,
          type: 'craft',
          isKnown: true,
          evidence: evidenceText,
          confidence: 0.95,
        });
        return craft.name;
      }
      // Novel craft concept - preserve artisan provided concept
      concepts.push({
        name: 'craft_type',
        value: val,
        type: 'craft',
        isKnown: false,
        evidence: evidenceText,
        confidence: 0.85,
      });
      return val;
    }

    if (fieldDef.name === 'category' && typeof val === 'string') {
      const cat = this.ontologyRegistry.findCategory(val);
      return cat ? cat.id : val;
    }

    if (fieldDef.name === 'material') {
      const rawList = Array.isArray(val) ? val : [val];
      const groundedList: string[] = [];

      for (const item of rawList) {
        const itemStr = String(item).trim();
        if (!itemStr) continue;

        const canonicalMaterial = this.ontologyRegistry.findMaterial(itemStr);
        if (canonicalMaterial) {
          groundedList.push(canonicalMaterial);
          concepts.push({
            name: 'material',
            value: canonicalMaterial,
            type: 'material',
            isKnown: true,
            evidence: itemStr,
            confidence: 0.95,
          });
        } else {
          // Novel artisan material (e.g. natural dyes, coconut shell, terracotta, jute) - preserve!
          groundedList.push(itemStr);
          concepts.push({
            name: 'material',
            value: itemStr,
            type: 'material',
            isKnown: false,
            evidence: itemStr,
            confidence: 0.85,
          });
        }
      }

      return fieldDef.type === 'array' ? groundedList : groundedList[0];
    }

    if (fieldDef.name === 'product_name' && typeof val === 'string') {
      concepts.push({
        name: 'product_name',
        value: val,
        type: 'product_concept',
        isKnown: false,
        evidence: evidenceText,
        confidence: 0.9,
      });
      return val;
    }

    return val;
  }

  /**
   * Generates a conversational follow-up question for the first missing required field
   */
  private generateFallbackFollowUp(missingField: string): string {
    const fieldDef = this.schemaRegistry.getField(missingField);
    const desc = fieldDef?.description || missingField;

    switch (missingField) {
      case 'price':
        return 'What price would you like to charge for this product?';
      case 'product_name':
        return 'What is the name or title of your craft product?';
      case 'material':
        return 'What materials are used to make this item?';
      case 'craft_type':
        return 'What is the craft discipline or style for this item?';
      case 'category':
        return 'Which category does this product belong to?';
      default:
        return `Could you please provide the ${desc}?`;
    }
  }

  public setLLMProvider(provider: ILLMProvider): void {
    this.llmProvider = provider;
  }
}

export const defaultNLUEngine = new NLUEngine();
