import type {
  NLUExtractionResult,
  NLUProcessOptions,
  ExtractedEntity,
  IntentResult,
} from './types.js';
import type { ILLMProvider } from '../../providers/llm/llmProvider.interface.js';
import { defaultLLMProvider } from '../../providers/llm/llmProvider.factory.js';
import { DynamicSchemaRegistry, defaultSchemaRegistry } from '../../schemas/dynamicSchema.js';
import { IntentRegistry, defaultIntentRegistry } from './intentRegistry.js';
import { OntologyRegistry, defaultOntologyRegistry } from '../../ontology/ontologyRegistry.js';
import { DeterministicExtractor } from './deterministicExtractor.js';
import { DynamicPromptBuilder } from './dynamicPromptBuilder.js';
import { ValidationError } from '../../utils/errors.js';
import { logger } from '../../utils/logger.js';

interface LLMOutputShape {
  intent?: string;
  confidence?: number;
  isCorrection?: boolean;
  language?: string;
  entities?: Record<string, unknown>;
}

export class NLUEngine {
  private schemaRegistry: DynamicSchemaRegistry;
  private intentRegistry: IntentRegistry;
  private ontologyRegistry: OntologyRegistry;
  private llmProvider: ILLMProvider;

  constructor(options?: {
    schemaRegistry?: DynamicSchemaRegistry;
    intentRegistry?: IntentRegistry;
    ontologyRegistry?: OntologyRegistry;
    llmProvider?: ILLMProvider;
  }) {
    this.schemaRegistry = options?.schemaRegistry || defaultSchemaRegistry;
    this.intentRegistry = options?.intentRegistry || defaultIntentRegistry;
    this.ontologyRegistry = options?.ontologyRegistry || defaultOntologyRegistry;
    this.llmProvider = options?.llmProvider || defaultLLMProvider;
  }

  /**
   * Main entry point to process natural artisan utterance into structured NLU result
   */
  public async process(
    text: string,
    options?: NLUProcessOptions
  ): Promise<NLUExtractionResult> {
    if (!text || !text.trim()) {
      throw new ValidationError('Input utterance cannot be empty');
    }

    const cleanText = text.trim();
    logger.debug({ text: cleanText, sessionId: options?.sessionId }, 'Processing NLU utterance');

    // 1. Deterministic Extraction
    const deterministic = DeterministicExtractor.extract(cleanText, this.ontologyRegistry);

    // 2. Build Dynamic System Prompt reflecting active configuration
    const systemPrompt = DynamicPromptBuilder.buildNLUSystemPrompt(
      this.schemaRegistry,
      this.intentRegistry,
      this.ontologyRegistry
    );

    // 3. LLM Semantic Understanding
    let llmResult: LLMOutputShape = {};
    try {
      const response = await this.llmProvider.generateStructured<LLMOutputShape>(
        cleanText,
        systemPrompt
      );
      llmResult = response.data || {};
    } catch (error) {
      logger.warn(
        { err: error, text: cleanText },
        'LLM semantic parsing failed, falling back to deterministic processing'
      );
    }

    // 4. Determine Intent
    const intentName =
      llmResult.intent ||
      (deterministic.isCorrectionCandidate ? 'CORRECT_INFORMATION' : 'CREATE_PRODUCT');
    const intentConfidence = llmResult.confidence ?? 0.85;
    const isCorrection = Boolean(llmResult.isCorrection || deterministic.isCorrectionCandidate);

    const intent: IntentResult = {
      name: intentName,
      confidence: intentConfidence,
    };

    // 5. Anti-Hallucination: Filter out any entities not defined in active Dynamic Schema
    const configuredFieldNames = new Set(this.schemaRegistry.getFields().map((f) => f.name));
    const validLLMEntities: Record<string, unknown> = {};

    if (llmResult.entities && typeof llmResult.entities === 'object') {
      for (const [key, val] of Object.entries(llmResult.entities)) {
        if (configuredFieldNames.has(key)) {
          validLLMEntities[key] = val;
        } else {
          logger.warn(
            { field: key, value: val },
            'Discarded ungrounded/unconfigured entity generated by LLM'
          );
        }
      }
    }

    // Explicit user evidence & deterministic ontology extraction takes precedence over LLM
    const mergedEntities: Record<string, unknown> = {
      ...validLLMEntities,
      ...deterministic.entities,
    };

    const entityDetails: ExtractedEntity[] = [...deterministic.entityDetails];
    for (const [key, value] of Object.entries(validLLMEntities)) {
      if (!deterministic.entities[key]) {
        entityDetails.push({
          field: key,
          value,
          evidence: cleanText,
          confidence: 0.85,
          source: 'LLM_EXTRACTION',
        });
      }
    }

    // 6. Normalization
    const normalizedEntities = this.schemaRegistry.normalizeDraft(mergedEntities);

    // 7. Calculate overall product draft state if contextual draft provided
    const effectiveDraft = options?.currentDraft
      ? { ...options.currentDraft, ...normalizedEntities }
      : normalizedEntities;

    // 8. Dynamic Validation & Missing Fields
    const validation = this.schemaRegistry.validateDraft(effectiveDraft);
    const missingFields = this.schemaRegistry.getMissingFields(effectiveDraft);

    const detectedLanguage =
      llmResult.language || deterministic.detectedLanguage || options?.languageHint || 'en';

    return {
      intent,
      entities: normalizedEntities,
      entityDetails,
      detectedLanguage,
      isCorrection,
      overallConfidence: Math.min(intentConfidence, 0.95),
      validation,
      missingFields,
      rawText: cleanText,
    };
  }

  public setLLMProvider(provider: ILLMProvider): void {
    this.llmProvider = provider;
  }
}

export const defaultNLUEngine = new NLUEngine();
